name: CI to Docker Hub

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*" 
jobs: 
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Set output
         id: vars
         run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_HUB_USERNAME }} 
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

       - name: Build&Push API
         id: docker_build_api
         uses: docker/build-push-action@v2
         with:
           context: ./server
           file: server/Dockerfile
           push: true
           tags: trybefore/bildenettside:api-${{ steps.vars.outputs.tag }}
       - name: Build&Push Client
         id: docker_build_client
         uses: docker/build-push-action@v2
         with:
           context: ./quasar-client
           file: quasar-client/Dockerfile
           push: true
           tags: trybefore/bildenettside:client-${{ steps.vars.outputs.tag }}
       - name: Image Digests
         run: echo ${{ steps.docker_build_api.outputs.digest }} && echo ${{ steps.docker_build_client.outputs.digest }}   
         
